GET http://localhost:3000/usuarios

###
GET http://localhost:3000/usuarios/abd

###
POST http://localhost:3000/usuarios
content-type: application/json

{
    "nombre": "andres",
    "apellido": "Perez",
    "email": "julionnn@gmail.com"
}

###
PUT http://localhost:3000/usuarios/2
content-type: application/json

{
    "nombre": "andres",
    "apellido": "Aguilar",
    "email": "julionn@gmail.com"
}