GET http://localhost:3000/users/

####
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users/
Content-Type: application/json

{
    "username": "fer",
    "password": "fer321",
    "email": "fer.ac@ittux.edu.mx"
}

###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "username": "Dennis.js"
}

###
DELETE http://localhost:3000/users/4

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "fer",
  "password": "$2b$10$k9XUYE9INgfYMj/BE84u3OvtPZlMz2M4Tqxj2K1rgWa3qbcDHoGAu"
}