### Mostrar todos los miembros de staff
GET http://localhost:3000/staff

### Mostrar un miembro específico de staff por ID
GET http://localhost:3000/staff/3

### Agregar un nuevo miembro a staff
POST http://localhost:3000/staff
Content-Type: application/json

{
  "first_name": "Dennis",
  "last_name": "Hoffman",
  "birth_date": "2003-03-16",
  "gender": "M",
  "phone_number": "1234567890",
  "email": "breyi0713@gamil.com",
  "address": "las rampas",
  "is_active": true,
  "user_id": 4
}

### Actualizar un miembro específico de staff
PUT http://localhost:3000/staff/2
Content-Type: application/json

{
  "first_name": "Bruno",
  "last_name": "Mars",
  "birth_date": "1985-10-08",
  "gender": "M",
  "phone_number": "1234567891",
  "email": "brunito@gmail.com",
  "address": "sabrá dios donde vive",
  "is_active": true,
  "user_id": 4
}

### Eliminar un miembro específico de staff por ID
DELETE http://localhost:3000/staff/4