### Mostrar todo staff
GET http://localhost:3000/staff

### Mostrar staff por ID
GET http://localhost:3000/staff/2

### Agregar a staff
POST http://localhost:3000/staff
Content-Type: application/json

{
  "first_name": "jesus",
  "last_name": "Garcia",
  "birth_date": "2003-03-03",
  "gender": "M",
  "phone_number": "2871234560",
  "email": "gg@gmail.com",
  "address": "loma bonita",
  "user_id": 4
}

### Actualizar staff
PUT http://localhost:3000/staff/2
Content-Type: application/json

{
  "first_name": "Maria",
  "last_name": "isabel",
  "birth_date": "2000-10-17",
  "gender": "F",
  "phone_number": "2871111111",
  "email": "mari@gmail.com",
  "address": "cdmx",
  "user_id": 3
}

### Eliminar staff 
DELETE http://localhost:3000/staff/3