POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "ines@tuxtepec.tecnm",
    "password": "123ines"
}

//{
 //   "email": "dennis@tuxtepec.tecnm",
   // "password": "123dennis"
//}

###
GET http://localhost:3000/users/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaXNfYWRtaW4iOjAsImlhdCI6MTczNDAyMzM1NCwiZXhwIjoxNzM0MDIzNjU0fQ.pLgNQajoHZnshWnzukiT_6BachcTpCmQ4-o5HHqkV_A