GET http://localhost:3000/pokemons

### 
GET http://localhost:3000/pokemons/2

### crear Tipo de contenido de la 
POST http://localhost:3000/pokemons 
Content-Type: : application/json

{
"nombre": "Sergio", 
"image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/6.svg"
}

### 
PUT http://localhost:3000/pokemons/1 
Content-Type: : application/json

{
"nombre": "Mega-Charizard", 
"image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/6-mega.svg"
}

### eliminar ELIMINAR 
DELETE http://localhost:3000/pokemons/155