GET http://localhost:3000/pokemons

###
GET http://localhost:3000/pokemons/play

### 
GET http://localhost:3000/pokemons/2

###  
POST http://localhost:3000/pokemons 
Content-Type: : application/json

{
"nombre": "DENNIS", 
"image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/6.svg"
}

### 
PUT http://localhost:3000/pokemons/1 
Content-Type: : application/json

{
"nombre": "Mega-Charizard", 
"image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/6-mega.svg"
}

###
DELETE http://localhost:3000/pokemons/155