GET http://localhost:3000/users

###
GET http://localhost:3000/users/2

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "first_name": "fernando",
    "last_name": "Hernandez",
    "email": "dennis@tuxtepec.tecnm",
    "password": "123dennis"
}

###
PUT http://localhost:3000/users/2
Content-Type: application/json

{
    "first_name": "fernando",
    "last_name": "Hernandez",
    "email": "dennis@tuxtepec.tecnm",
    "password": "123dennis"
}

###
DELETE http://localhost:3000/users/2
